matter-labs/era-compiler-vyper

.github/workflows/build_release.yaml

Add msys installation on Windows host for release workflow
It was mistakenly removed during refactoring process

ci: fix msys installation on Windows

---

Cargo.lock

Update dependencies to pull the newest changes from era-zkEVM-assembly.
These changes include assembler support for jump tables.

Pull changes from era-zkEVM-assembly

---

CHANGELOG.md
src/zkvyper/arguments.rs

Prints help if no arguments are provided.
To make behavior similar to `solc`.

Print help if no arguments are provided

---

.cargo/config.toml
CHANGELOG.md
Cargo.lock
Cargo.toml
LLVM.lock
src/project/contract/vyper/expression/instruction/assert.rs
src/project/contract/vyper/expression/instruction/clamp.rs
src/project/contract/vyper/expression/instruction/create.rs
src/project/contract/vyper/expression/instruction/exit_to.rs
src/project/contract/vyper/expression/instruction/goto.rs
src/project/contract/vyper/expression/instruction/if.rs
src/project/contract/vyper/expression/instruction/immutable.rs
src/project/contract/vyper/expression/instruction/label.rs
src/project/contract/vyper/expression/instruction/mod.rs
src/project/contract/vyper/expression/instruction/offset.rs
src/project/contract/vyper/expression/instruction/repeat.rs
src/project/contract/vyper/expression/instruction/set.rs
src/project/contract/vyper/expression/instruction/with.rs
src/project/contract/vyper/expression/mod.rs
src/project/contract/vyper/function.rs

Update to LLVM 17

---

.github/workflows/test-cli.yaml
.github/workflows/test.yaml
cli-tests/package-lock.json
cli-tests/package.json
cli-tests/src/contracts/zkasm/contract.zkasm
cli-tests/src/entities.ts
cli-tests/src/helper.ts
cli-tests/tests/common.test.ts
cli-tests/tests/output-dir.test.ts
cli-tests/tests/zkasm.test.ts

Tests for:
- output-dir
- zkasm
+ TMP dir for new test
+ extended output file name detection

test: initial commit with tests

---

.github/actions/build-llvm/action.yml
.github/actions/cli-tests/action.yml
.github/actions/unit-tests/action.yml
.github/workflows/build_release.yaml
.github/workflows/test-cli.yaml
.github/workflows/test.yaml

Use the new LLVM builder with --target-env option + small CI fixes.
To get the latest builder from cargo, facilitate its updates in the future, and simplify CI.

ci: use new llvm builder

---

CONTRIBUTING.md
README.md
src/project/contract/vyper/ast.rs
src/project/contract/vyper/expression/instruction/deploy.rs

Fixes README.md after LLVM 17 and builder updates:
To fix documentation issues.

docs: update setup and build instructions

---

.github/actions/build-llvm/action.yml

Update llvm builder to 1.0.25 (renaming from zkevm-llvm to zksync-llvm).
To fix musl download issue and correspond to the latest naming conventions requirements.

ci: update llvm builder to 1.0.25

---

Cargo.lock
Cargo.toml
src/lib.rs
src/project/contract/vyper/expression/instruction/mod.rs
src/tests/unsupported_opcodes.rs
src/vyper/mod.rs

Adds the EXTCODECOPY support.
Such precompile was added to System Contracts.

feat: support EXTCODECOPY

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/lib.rs
src/process/mod.rs
src/project/contract/llvm_ir.rs
src/project/contract/metadata.rs
src/project/contract/mod.rs
src/project/contract/vyper/expression/instruction/assert.rs
src/project/contract/vyper/expression/instruction/clamp.rs
src/project/contract/vyper/expression/instruction/create.rs
src/project/contract/vyper/expression/instruction/exit_to.rs
src/project/contract/vyper/expression/instruction/goto.rs
src/project/contract/vyper/expression/instruction/if.rs
src/project/contract/vyper/expression/instruction/immutable.rs
src/project/contract/vyper/expression/instruction/label.rs
src/project/contract/vyper/expression/instruction/mod.rs
src/project/contract/vyper/expression/instruction/offset.rs
src/project/contract/vyper/expression/instruction/repeat.rs
src/project/contract/vyper/expression/instruction/return.rs
src/project/contract/vyper/expression/instruction/revert.rs
src/project/contract/vyper/expression/instruction/seq.rs
src/project/contract/vyper/expression/instruction/set.rs
src/project/contract/vyper/expression/instruction/with.rs
src/project/contract/vyper/expression/mod.rs
src/project/contract/vyper/function.rs
src/project/contract/vyper/mod.rs
src/zkvyper/main.rs

Updates interfaces according to [this PR](https://github.com/matter-labs/era-compiler-solidity/pull/100).

chore: remove Clone from Dependency

---

.github/workflows/test.yaml
Cargo.lock
Cargo.toml
cli-tests/tests/common.test.ts
cli-tests/tests/output-dir.test.ts
cli-tests/tests/overwrite.test.ts

Add advanced cargo checks: `fmt`, `clippy`, `udeps` (unused dependencies), `audit`

ci: add advanced cargo checks including fmt, clippy, and audit

---

.github/actions/cli-tests/action.yml
.github/actions/install-vyper/action.yml
.github/workflows/test.yaml
CHANGELOG.md
Cargo.lock
Cargo.toml
cli-tests/src/contracts/vyper/contract.vy
cli-tests/src/contracts/vyper/ecrecover.vy
cli-tests/src/contracts/vyper/extcode.vy
cli-tests/src/contracts/vyper/txorigin.vy
src/const.rs
src/lib.rs
src/metadata/function.rs
src/project/contract/vyper/expression/instruction/exit_to.rs
src/project/contract/vyper/expression/instruction/goto.rs
src/project/contract/vyper/expression/instruction/label.rs
src/project/contract/vyper/expression/mod.rs
src/project/contract/vyper/function.rs
src/project/contract/vyper/mod.rs
src/tests/mod.rs
src/vyper/mod.rs
src/vyper/standard_json/input/mod.rs
src/vyper/standard_json/input/settings/mod.rs
src/vyper/standard_json/input/settings/optimize.rs
src/zkvyper/arguments.rs
src/zkvyper/main.rs

Support for vyper 0.4.0.
It has been released by the Vyper team recently.

feat: support vyper v0.4.0

---

.github/workflows/release.yaml

Add -gnu in the windows executable suffix
To align with plugins.

chore: add -gnu in the windows executable suffix

---

CHANGELOG.md
src/project/contract/vyper/expression/instruction/repeat.rs

Fixes the ignored loop range bounds.

fix: ignored loop range bounds

---

.github/actions/build/action.yml
.github/actions/unit-tests/action.yml
.github/workflows/release.yaml
.github/workflows/sanitizers.yaml
.github/workflows/test.yaml
Cargo.lock

Aligning `zksolc` and `zkvyper` CI workflows.

ci: update docker, add gnu targets, support coverage

---

CHANGELOG.md
Cargo.lock
Cargo.toml
LLVM.lock

release: v1.5.4

---

.github/workflows/depenencies.yaml

Add dependencies verification workflow with:
Tested in `era-compiler-common`:
https://github.com/matter-labs/era-compiler-common/actions/runs/10717531440/job/29717419792
To allow testing in dependency repositories flawlessly.

ci: update depencencies verification workflow

---

.github/workflows/depenencies.yaml
.github/workflows/release.yaml
.github/workflows/sanitizers.yaml
.github/workflows/test.yaml

To return CI to proper state after runners rework.

ci: update runner labels to high performance

---

.github/workflows/sanitizers.yaml
.github/workflows/test.yaml

Enables RelWithDebInfo for tests and sanitizer.
It provides more diagnostics for potential issues.

feat: enable RelWithDebInfo for tests and sanitizer

---

.github/workflows/sanitizers.yaml
.github/workflows/test.yaml
Cargo.lock

Fix unit tests and supports debug/release execution.

ci: support debug and release unit tests

---

.github/workflows/dependencies.yaml

Fix dependencies workflow.
Unit tests action was moved to the common repo, update the workflow accordingly.

ci: fix dependencies workflow with common unit tests

---

.github/workflows/dependencies.yaml

Fixes crate name for `llvm-sys` dependency.
To fix failure in dependency definition for `llvm-sys` https://github.com/matter-labs/era-compiler-solidity/actions/runs/11054727456/job/30712206141

ci: fix dependencies workflow llvm-sys dependency

---

CHANGELOG.md
Cargo.lock

release: v1.5.5

---

LLVM.lock

fix: update LLVM.lock

---

CHANGELOG.md
Cargo.lock
Cargo.toml

release: v1.5.6

---

Cargo.lock
src/project/contract/vyper/expression/instruction/mod.rs

Update the deps and fixes an intrinsic name.

fix: deps and the memmove intrinsic name

---

CHANGELOG.md
Cargo.lock
Cargo.toml
LLVM.lock

release: version 1.5.7

---

.github/workflows/secrets-scanner.yaml
.github/workflows/test.yaml

Add required status check to testing workflow.
To be able to use auto-merge feature and not let broken PRs to be merged in main.

ci: add required status check to testing workflow

---

.github/workflows/test.yaml
Cargo.lock
Cargo.toml
deny.toml
src/zkvyper/arguments.rs
src/zkvyper/main.rs
tests/cli/basic.rs
tests/cli/debug_output_dir.rs
tests/cli/disable_vyper_optimizer.rs
tests/cli/eravm_assembly.rs
tests/cli/fallback.rs
tests/cli/format.rs
tests/cli/llvm_debug_log.rs
tests/cli/llvm_ir.rs
tests/cli/llvm_verify_each.rs
tests/cli/metadata_hash.rs
tests/cli/optimization.rs
tests/cli/output_dir.rs
tests/cli/overwrite.rs
tests/cli/suppress.rs
tests/cli/vyper.rs

Fixes https://github.com/matter-labs/era-compiler-solidity/issues/206

fix: replace structopt with clap

---

src/zkvyper/arguments.rs

chore: fix typo

---

CHANGELOG.md
Cargo.lock
LLVM.lock
README.md

Tests the v1.5.8 release build.

release: v1.5.8

---

.github/workflows/release.yaml

Fix llvm version check in release workflow.

ci: fix llvm version check in release workflow

---

.github/workflows/release.yaml

Disable prerelease and mark the new release as the `latest`.

ci: disable prerelease and mark new release as latest

---

src/build/mod.rs
src/project/contract/llvm_ir.rs

Fixes a sanitizer error with minimal proxy.

fix: the sanitizer error with minimal proxy

---

Cargo.lock
Cargo.toml

Adds the support for EVM immutables.

feat(evm): update deps after immutables support

---

rust-toolchain.toml

Update stable rustc from 1.82 to 1.83.

chore: update stable rustc from 1.82 to 1.83

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/project/mod.rs

chore: update deps

---

.cargo/config.toml
.github/workflows/ccache-regen.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
.gitmodules
CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
docs/src/01-installation.md
rust-toolchain.toml

feat: update to LLVM 19

---

.gitmodules
CHANGELOG.md
Cargo.lock

chore: release v1.5.11
