matter-labs/era-compiler-vyper

- .github/pull_request_template.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/tests/builtins.rs
- src/tests/unsupported_opcodes.rs
- src/vyper/mod.rs
This patch enables the vyper v0.3.10 support.
Vyper 0.3.10 features were already supported but not enabled yet, as the updated was not officially released yet.
> Enable the vyper v0.3.10 support

- .github/workflows/build_release.yaml
- .gitignore
Migrates the CI workflows from the private repos.
We are going to release all binaries from this open-source repository from now on.
> ci: add the binaries release workflow

- Cargo.lock
- Cargo.toml
Adds `optnone` and `noinline` attributes to all functions if middle-end optimizations are disabled.
It should disable some RAM-demanding LLVM passes which cause OOM on large unoptimized codebases.
> Add noinline+optnone attributes in M0

- .github/workflows/unit-tests.yaml
Fixes [CPR-1273](https://linear.app/matterlabs/issue/CPR-1273/github-action-for-zkvyper-unit-tests)
Add unit tests execution in CI with each PR and merge to the trunk.
Supported targets:
* Macos x86_64
* Macos ARM64
* Linux x86_64
* Windows Mingw64
> KNOWN RESTRICTION - not supported target: `Linux ARM64` due to lack of the `vyper` executable built for Linux ARM64.
Results are reported as PR checks, e.g.:
As well as PR auto-updated comments:
For now, 8 unit tests exist and all pass on all available platforms.
In order to keep the trunk always stable, introduce unit tests quality gates on the PR level as well as make sure that unit tests in the `main` branch are always working after the merge.
> ci: add unit tests workflow

- .github/workflows/build_release.yaml
- .github/workflows/unit-tests.yaml
Update Linux docker image to `ubuntu22-llvm15-latest` from public Dockerhub registry.
The previous `jammy` image was private preventing forks to be properly tested.
> ci: update linux docker image to public ubuntu22-llvm15-latest

- src/process/mod.rs
In the sentence "The overriden executable name used when the compiler is run as a library," the word "overriden" appears to be spelled incorrectly. The correct spelling should be "overridden," indicating that something has been replaced or modified. Therefore, the corrected sentence is:
"The overridden executable name used when the compiler is run as a library."
> fix: misspelled word

- .github/workflows/unit-tests.yaml
Fix CI unit tests results parsing error caused by `lxml` libraries on MacOS ARM64 host:
```
dlopen(/Users/hetzner/actions-runner/_work/era-compiler-solidity/era-compiler-solidity/enricomi-publish-action-venv/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace (_exsltDateXpathCtxtRegister)
```
The fix for now is to use the previous action version before `lxml` was updated to `5.1.0` causing these issues on MacOS ARM64 hosts.
To restore unit tests and CI checks back to normal.
> ci: fix unit tests results parsing for macos arm64

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/project/contract/vyper/expression/instruction/mod.rs
Uses memmove for same address spaces.
memcpy doesn't work with overlapping memory regions.
> Replace memcpy with memmove

- .github/workflows/build_release.yaml
Restores proper sending of Slack notifications about new releases after [ITS-392](https://linear.app/matterlabs/issue/ITS-392/slack-webhook-for-compilers-repositories) fix.
To notify the other teams about new `zkvyper` releases.
> ci: restore slack notifications with new token

- .github/actions/build-llvm/action.yml
CI: `apt update` is required for docker container jobs to install `ccache` properly. See [here](https://github.com/hendrikmuhs/ccache-action?tab=readme-ov-file#usage).
Fixing CI failures.
It worked before because the Docker container was not standardized, but after cleaning it up, this is required now.
> ci: fix ccache installation on Linux with new docker

- .github/actions/cli-tests/action.yml
Fix for race conditions issues for CLI tests
To prevent future race conditions for CLI tests if same output directory is in use.
> ci: run cli tests in band to fix concurrency issues

- src/tests/mod.rs
- src/vyper/mod.rs
- src/zkvyper/main.rs
Checks for the `vyper` binary only in Vyper mode.
The `vyper` binary was checked even in `--zkasm` mode.
> Validate vyper only for Vyper input

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/zkvyper/arguments.rs
- src/zkvyper/main.rs
Adds the jump table density threshold optimizer parameter.
This parameter is required for the jump table optimization, which is useful for the EVM interpreter on EraVM.
> Add the jump table density threshold

- CHANGELOG.md
- src/build/contract.rs
- src/vyper/combined_json/mod.rs
Missing `--overwrite` now returns an error.
Earlier, it would print an error and return exit code 0.
> Missing `--overwrite` now returns an error

- CHANGELOG.md
- src/build/contract.rs
Prints bytecode to --output-dir as a hex string.
Binary format that was printed before, was unreadable and unusable by the tools.
> Print bytecode to --output-dir as a hex string

- CHANGELOG.md
- src/lib.rs
- src/zkvyper/main.rs
Fixes the broken pipe error.
It is now possible to redirect the process output to another process.
> fix: the broken pipe error

- .cargo/config.toml
- Cargo.toml
Use an unique name for compiler-rt links for `aarch64-unknown-linux-arm` target.
To solve the linkage issue when both `zksolc` and `zkvyper` are used as a dependency.
> build: use unique name for crt links

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/process/mod.rs
- src/vyper/mod.rs
- src/vyper/version.rs
- src/zkvyper/main.rs
Makes `vyper` a singleton, initializing it and requesting `version` only once.
It must reduce the number of spawned child processes, improving the general performance.
> feat: make vyper a singleton

- src/process/mod.rs
- src/vyper/mod.rs
Reads child process data in another thread.
It should help with the excessive RAM usage in `solc`, which probably collects all its output before `zksolc` starts reading it.
> feat: read child process output in another thread

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli-tests/tests/llvm-ir.test.ts
- src/lib.rs
- src/process/input.rs
- src/process/mod.rs
- src/project/contract/llvm_ir.rs
- src/project/contract/metadata.rs
- src/project/contract/mod.rs
- src/project/contract/vyper/expression/instruction/deploy.rs
- src/project/contract/vyper/expression/instruction/label.rs
- src/project/contract/vyper/expression/instruction/mod.rs
- src/project/contract/vyper/expression/instruction/seq.rs
- src/project/contract/vyper/expression/mod.rs
- src/project/contract/vyper/mod.rs
- src/project/contract/zkasm.rs
- src/project/mod.rs
- src/tests/mod.rs
- src/zkvyper/arguments.rs
- src/zkvyper/main.rs
Allows passing arbitrary LLVM arguments in FE.
It is needed for experiments with the optimizer, and for debugging.
> feat: pass arbitrary options to LLVM

- .github/workflows/release.yaml
Dynamically create a build/release matrix instead of skipping steps.
* [Test with all jobs](https://github.com/matter-labs/era-compiler-vyper/actions/runs/9404515340)
* [Test with 3 jobs](https://github.com/matter-labs/era-compiler-vyper/actions/runs/9404507501)
* [Test with no jobs](https://github.com/matter-labs/era-compiler-vyper/actions/runs/9404548872)
This will not overload runners just to skip all steps and speed up builds.
Related to [CPR-1733](https://linear.app/matterlabs/issue/CPR-1733/improve-zksolczkvyper-matrix-jobs-to-disable-completely-if-the)
> ci: add proper matrix configuration when platforms are off

- .github/workflows/release.yaml
Fixes an issue with release generation if `ref` is not specified.
GH API cannot take short sha for commit.
> ci: fix release issue with empty ref parameter

- .github/actions/build/action.yml
- .github/workflows/release.yaml
Related to [CPR-1379](https://linear.app/matterlabs/issue/CPR-1739/fix-the-changelog-publishing)
There always can be some unexpected special symbols in the changelog that are impossible to filter or escape properly while manually creating the Slack notification from the changelog entry This PR is a proposal to never do this, and instead use GitHub <--> Slack integration to subscribe to the `releases` in the repository forwarding the required release notification in the common group when the release is out and verified.
> ci: fix release with special symbols in changelog

- cli-tests/tests/common.test.ts
- cli-tests/tests/format.test.ts
- cli-tests/tests/output-dir.test.ts
- cli-tests/tests/overwrite.test.ts
- src/build/mod.rs
- src/zkvyper/main.rs
Fixes some unit tests and combined JSON output on Windows.
> fix: combined_json format check

- CHANGELOG.md
- cli-tests/tests/eravm-assembly.test.ts
- cli-tests/tests/format.test.ts
- cli-tests/tests/llvm-ir.test.ts
- src/build/mod.rs
- src/lib.rs
- src/message_type.rs
- src/process/input.rs
- src/process/mod.rs
- src/project/contract/eravm_assembly.rs
- src/project/contract/llvm_ir.rs
- src/project/contract/mod.rs
- src/project/contract/vyper/ast.rs
- src/project/contract/vyper/mod.rs
- src/project/mod.rs
- src/tests/mod.rs
- src/vyper/combined_json/mod.rs
- src/vyper/mod.rs
- src/vyper/standard_json/output/mod.rs
- src/zkvyper/arguments.rs
- src/zkvyper/main.rs
Adds the support for compiling multiple contracts written in LLVM IR and EraVM assembly.
> feat: compile multiple IR contracts

- .github/actions/build/action.yml
- .github/actions/unit-tests/action.yml
- .github/workflows/sanitizers.yaml
- Cargo.lock
Support builds and unit tests run with sanitizers:
* As per request triggered manually from [actions page](https://github.com/matter-labs/era-compiler-solidity/actions/workflows/sanitizers.yaml)
* Weekly with address sanitizer
[Testing workflow](https://github.com/matter-labs/era-compiler-vyper/actions/runs/9680717020/job/26709525283?pr=73)
To add a capability to find more bugs using sanitizers.
> ci: support unit tests with sanitizers

- .github/actions/install-vyper/action.yml
Add more vyper executables for unit tests:
* `0.3.3`
* `0.3.9`
* `0.3.10`
* `0.4.0`
To catch incompatibilities with older vyper versions.
> ci: add more vyper executables available for unit tests

- .github/workflows/release.yaml
Add support for universal MacOS binary (x64 + arm64). For now, it is added additionally to existing arm64 and amd64 binaries.
[Testing workflow](https://github.com/matter-labs/era-compiler-vyper/actions/runs/9746432772)
> release: support universal macosx binary

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/build/mod.rs
Fixes the path normalization crash with contracts containing the minimal proxy.
> fix: the minimal proxy path error

- .github/workflows/release.yaml
Add version guard that cargo package, created tag, and version in changelog must be equal when releasing.
To prevent discrepancies between `--version` output and releases.
> release: add version guard between cargo, tag and changelog

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/project/contract/vyper/expression/instruction/assert.rs
- src/project/contract/vyper/expression/instruction/clamp.rs
- src/project/contract/vyper/expression/instruction/mod.rs
- src/project/contract/vyper/expression/mod.rs
Burn all gas with assert unreachable.
Fixes https://github.com/matter-labs/era-compiler-vyper/issues/83
It has been translated to the equivalent of `REVERT` instead of `INVALID`.
> fix: burn all gas with assert unreachable

- codecov.yml
Disable explicit coverage checks that can fail CI.
For now, coverage is only for informational purposes.
> ci: do not fail if coverage checks failed

- README.md
(Mostly copied from https://github.com/matter-labs/era-compiler-solidity/pull/124.)
* Update ReadMe now that musl is not needed.
* Note support for Linux ARM64.
* Harmonize case for musl and ARM64.
* Explain LLVM_SYS_170_PREFIX.  (Should also be changed in era-compiler-solidity.)
> docs: update ReadMe now that musl is not needed; support Linux ARM64

- Cargo.lock
- Cargo.toml
- src/const.rs
- src/project/contract/eravm_assembly.rs
- src/project/contract/vyper/expression/mod.rs
- src/tests/mod.rs
- src/zkvyper/main.rs
Moves some LLVM-unrelated definitions to [the common crate](https://github.com/matter-labs/era-compiler-common/pull/17).
They can be useful for some crates that doesn't want to depend on LLVM.
> feat: move LLVM-independent data to common

- Cargo.lock
- src/zkvyper/arguments.rs
- src/zkvyper/main.rs
Sets the `noinline` attribute for all calls in `-O0`.
It will prevent inlining of some runtime functions with `alwaysinline` attribute.
> feat: set noinline attribute for all calls in -O0

- CHANGELOG.md
- src/zkvyper/arguments.rs
- tests/cli/basic.rs
- tests/cli/debug_output_dir.rs
- tests/cli/disable_vyper_optimizer.rs
- tests/cli/eravm_assembly.rs
- tests/cli/fallback.rs
- tests/cli/llvm_debug_log.rs
- tests/cli/llvm_ir.rs
- tests/cli/llvm_verify_each.rs
- tests/cli/metadata_hash.rs
- tests/cli/optimization.rs
When no files provided, the error code is now 1.
It used to be 0, and it didn't match neither `vyper` nor other mainstream compilers.
> fix: error code when no input files provided

- .github/workflows/ccache-regen.yaml
- .github/workflows/dependencies.yaml
- .github/workflows/release.yaml
- .github/workflows/sanitizers.yaml
- .github/workflows/test.yaml
Rework the way we generate `ccache`.
This will simplify `ccache` regeneration and always take into account all new changes in the builder, env variables, build types, etc. LLVM will be cached and up to date each day for testing in PRs and new release generations.
> ci: add special workflow to regenerate ccache

- .github/actions/build/action.yml
- .github/workflows/release.yaml
Use custom tag in binary names for manual releases instead of branch names.
To have binaries with short and beautiful names for manual pre-releases.
> ci: use custom tag in binary names for manual releases

- .github/workflows/release.yaml
Fixes the universal binary pre-release.
It was broken when switching to custom tag suffixes.
> fix: the universal binary pre-release

- CHANGELOG.md
- src/zkvyper/arguments.rs
- src/zkvyper/main.rs
- tests/cli/llvm_options.rs
- tests/cli/mod.rs
Adds more resilience to `--llvm-options` parsing, and makes `--help` more informative.
> fix: fragile LLVM options parsing

- Cargo.lock
- Cargo.toml
- src/zkvyper/arguments.rs
- tests/cli/mod.rs
- tests/cli/version.rs
Fixes the broken `zkvyper --version` endpoint.
It was regressed after more argument validations were added.
> fix: the broken --version endpoint

- CHANGELOG.md
- src/build/mod.rs
- src/vyper/combined_json/extra_data.rs
- src/vyper/combined_json/mod.rs
In combined JSON output, wraps `project_metadata` into `extra_data`.
All contract objects are flattened and raised to the root of combined JSON output.
The plugin relies on it and treats all new fields as contracts unless they are explicitly excluded like `version` and `zk_version`.
The newly added `extra_data` object will be a safe haven for all new output fields we might need in the future.
> feat: wrap project metadata into extra data

- Cargo.lock
- src/const.rs
- src/project/contract/eravm_assembly.rs
- src/project/contract/llvm_ir.rs
- src/project/contract/vyper/mod.rs
Fixes the library linking indeterminism.
The bytecode is not equal depending on when libraries are linked: at compile time or deploy (post-compile) time.
> fix: library linking time indeterminism

- CHANGELOG.md
- Cargo.lock
- rust-toolchain.toml
- src/project/contract/vyper/expression/instruction/mod.rs
- src/project/contract/vyper/mod.rs
Uses contract code segment that was moved to [era-compiler-common](https://github.com/matter-labs/era-compiler-common).
It is required for some LLVM-independent crates such as the upcoming era-solc client.
> chore: move code segment to era-compiler-common

- .github/workflows/test.yaml
- deny.toml
To fix cargo deny license warnings and errors and make sure `required` check condition is always fullfilled.
> ci: update cargo deny config and enable PR tests for all files

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Cleares return data after calling `CREATE`/`CREATE2` (`ContractDeployer` system contract for EraVM).
It is cleared on EVM, but not on EraVM.
> fix(eravm): resets return data after calling CREATE

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Removes the branch replacing call(0x04) with memcopy.
> fix: remove the branch replacing call(0x04) with memcopy

- CHANGELOG.md
- src/const.rs
Update the minimal proxy contract assembly.
It's about 20% shorter after including all recent optimizations.
> chore: update the minimal proxy contract assembly

- .github/workflows/deploy-docs.yaml
Add `v` prefix to documentation website url.
To make docs url more beautiful `/v1.5.8` instead of `/1.5.8`.
> chore: add v prefix to documentation website url

- docs/js/version-box.js
Fix versions sorting order.
To `latest` go first, then from latest release to oldest.
> docs: fix versions sorting order

- docs/js/version-box.js
This PR updates the `version-box.js` file to use more optimized JavaScript code.
This PR should make the overall execution of this file faster and more robust, improving the documentation in general.
- [/] Tests for the changes have been added / updated.
- [/] Documentation comments have been added / updated.
- [/] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.
> docs: optimize version-box.js

- .github/workflows/release.yaml
Add compiler binaries [GitHub attestations ](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds)support.
It would allow binary users to use attestation information through `gh api` to check if compiler binaries were built in our repositories and by our workflows improving usage security.
Attestation example: https://github.com/matter-labs/era-compiler-solidity/attestations/4282238
> ci: add binaries attestation support

- Cargo.lock
- Cargo.toml
- LLVM.lock
- src/project/contract/llvm_ir.rs
- src/project/contract/vyper/expression/instruction/assert.rs
- src/project/contract/vyper/expression/instruction/clamp.rs
- src/project/contract/vyper/expression/instruction/create.rs
- src/project/contract/vyper/expression/instruction/exit_to.rs
- src/project/contract/vyper/expression/instruction/goto.rs
- src/project/contract/vyper/expression/instruction/if.rs
- src/project/contract/vyper/expression/instruction/immutable.rs
- src/project/contract/vyper/expression/instruction/label.rs
- src/project/contract/vyper/expression/instruction/mod.rs
- src/project/contract/vyper/expression/instruction/offset.rs
- src/project/contract/vyper/expression/instruction/repeat.rs
- src/project/contract/vyper/expression/instruction/return.rs
- src/project/contract/vyper/expression/instruction/revert.rs
- src/project/contract/vyper/expression/instruction/seq.rs
- src/project/contract/vyper/expression/instruction/set.rs
- src/project/contract/vyper/expression/instruction/with.rs
- src/project/contract/vyper/expression/mod.rs
- src/project/contract/vyper/function.rs
- src/project/contract/vyper/mod.rs
- src/project/dependency_data.rs
- src/project/mod.rs
Removes the old dependency handlers in order to support LLVM library linking.
> fix(evm): remove the old dependency handlers

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
1. Enables falling back to -Oz if the EVM runtime bytecode size is exceeded.
2. Enables the check for EVM runtime bytecode size of 24576 bytes.
> feat: enable fallback-Oz and check runtime code size

- .github/workflows/deploy-docs.yaml
Release docs only when a new release is published.
To overcome the situation when release is not created (e.g. binaries publishing failure), but the tag is.
> chore: release docs only when a new release is published

- CHANGELOG.md
- src/const.rs
- src/process/mod.rs
- src/zkvyper/main.rs
Sets the stack limit back to 64 MB to increase the resilience of recursive algorithms.
> fix: set the stack limit back to 64 MB

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- LICENSE-MIT
- LLVM.lock
- docs/src/02-command-line-interface.md
- docs/src/03-combined-json.md
- src/const.rs
- src/lib.rs
- src/process/input.rs
- src/process/mod.rs
- src/project/contract/eravm_assembly.rs
- src/project/contract/llvm_ir.rs
- src/project/contract/mod.rs
- src/project/contract/vyper/expression/mod.rs
- src/project/contract/vyper/mod.rs
- src/project/mod.rs
- src/zkvyper/arguments.rs
- src/zkvyper/main.rs
- tests/cli/metadata_hash.rs
- tests/cli/mod.rs
- tests/cli/no_bytecode_metadata.rs
- tests/common/mod.rs
Supports the CBOR payload with `vyper` compiler version at the end of bytecode.
It is usefull for contract verification purposes.
> feat: make IPFS hash and CBOR equivalent again

- docs/src/02-command-line-interface.md
Makes `--metadata-hash` more clear.
> fix: --metadata-hash docs

- .github/workflows/deploy-docs.yaml
- .github/workflows/release.yaml
Default `GITHUB_TOKEN` does not trigger any workflows for release generation. As we shouldn't use any private tokens, try to use `workflow_call` to trigger documentation update.
> ci: deploy docs after successful release by workflow call

- .github/workflows/release.yaml
Remove semver condition check for releases.
To allow use `main` branch for LLVM submodule.
> ci: remove semver condition for submodules during releases

- Cargo.lock
- Cargo.toml
Bumps sha2 to v0.10.9.
Can't update `revm` in compiler-tester otherwise.
> chore: bump zkevm_opcode_defs and sha2
